
package portafolio.gpvh.controlAccesoWS.mappingWsl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "consultaControlAcceso", targetNamespace = "http://controldeacceso.portafolio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaControlAcceso {


    /**
     * 
     * @param persona
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarPersona", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.GenerarPersona")
    @ResponseWrapper(localName = "generarPersonaResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.GenerarPersonaResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/generarPersonaRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/generarPersonaResponse")
    public String generarPersona(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona);

    /**
     * 
     * @param persona
     * @return
     *     returns portafolio.gpvh.controlAccesoWS.mappingWsl.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "externalLogin", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.ExternalLogin")
    @ResponseWrapper(localName = "externalLoginResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.ExternalLoginResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/externalLoginRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/externalLoginResponse")
    public Persona externalLogin(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona);

    /**
     * 
     * @param cantidadColumnas
     * @param fragmentoRut
     * @param fragmentoNombres
     * @return
     *     returns java.util.List<portafolio.gpvh.controlAccesoWS.mappingWsl.Persona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "busquedaPersonas", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.BusquedaPersonas")
    @ResponseWrapper(localName = "busquedaPersonasResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.BusquedaPersonasResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/busquedaPersonasRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/busquedaPersonasResponse")
    public List<Persona> busquedaPersonas(
        @WebParam(name = "fragmentoRut", targetNamespace = "")
        int fragmentoRut,
        @WebParam(name = "fragmentoNombres", targetNamespace = "")
        String fragmentoNombres,
        @WebParam(name = "cantidadColumnas", targetNamespace = "")
        int cantidadColumnas);

    /**
     * 
     * @param persona
     * @param dia
     * @return
     *     returns java.util.List<portafolio.gpvh.controlAccesoWS.mappingWsl.Marcacion>
     */
    @WebMethod(operationName = "AsistenciaPorDia")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AsistenciaPorDia", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.AsistenciaPorDia")
    @ResponseWrapper(localName = "AsistenciaPorDiaResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.AsistenciaPorDiaResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/AsistenciaPorDiaRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/AsistenciaPorDiaResponse")
    public List<Marcacion> asistenciaPorDia(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona,
        @WebParam(name = "dia", targetNamespace = "")
        XMLGregorianCalendar dia);

    /**
     * 
     * @param hasta
     * @param persona
     * @param desde
     * @return
     *     returns java.util.List<portafolio.gpvh.controlAccesoWS.mappingWsl.Marcacion>
     */
    @WebMethod(operationName = "AsistenciaPorRangoDeFecha")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AsistenciaPorRangoDeFecha", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.AsistenciaPorRangoDeFecha")
    @ResponseWrapper(localName = "AsistenciaPorRangoDeFechaResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.AsistenciaPorRangoDeFechaResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/AsistenciaPorRangoDeFechaRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/AsistenciaPorRangoDeFechaResponse")
    public List<Marcacion> asistenciaPorRangoDeFecha(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona,
        @WebParam(name = "desde", targetNamespace = "")
        XMLGregorianCalendar desde,
        @WebParam(name = "hasta", targetNamespace = "")
        XMLGregorianCalendar hasta);

    /**
     * 
     * @param persona
     * @param arg1
     * @return
     *     returns portafolio.gpvh.controlAccesoWS.mappingWsl.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "devolverHorasCompesadas", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.DevolverHorasCompesadas")
    @ResponseWrapper(localName = "devolverHorasCompesadasResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.DevolverHorasCompesadasResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/devolverHorasCompesadasRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/devolverHorasCompesadasResponse")
    public Persona devolverHorasCompesadas(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param persona
     * @param arg1
     * @return
     *     returns portafolio.gpvh.controlAccesoWS.mappingWsl.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consumirHorasCompesadas", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.ConsumirHorasCompesadas")
    @ResponseWrapper(localName = "consumirHorasCompesadasResponse", targetNamespace = "http://controldeacceso.portafolio.com/", className = "portafolio.gpvh.controlAccesoWS.mappingWsl.ConsumirHorasCompesadasResponse")
    @Action(input = "http://controldeacceso.portafolio.com/consultaControlAcceso/consumirHorasCompesadasRequest", output = "http://controldeacceso.portafolio.com/consultaControlAcceso/consumirHorasCompesadasResponse")
    public Persona consumirHorasCompesadas(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
