
package portafolio.gpvh.controlAccesoWS.mappingWsl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "consultaControlAcceso", targetNamespace = "http://controldeacceso.portafolio.com/", wsdlLocation = "http://35.237.92.42:8084/ControlDeAcceso/consultaControlAcceso?wsdl")
public class ConsultaControlAcceso_Service
    extends Service
{

    private final static URL CONSULTACONTROLACCESO_WSDL_LOCATION;
    private final static WebServiceException CONSULTACONTROLACCESO_EXCEPTION;
    private final static QName CONSULTACONTROLACCESO_QNAME = new QName("http://controldeacceso.portafolio.com/", "consultaControlAcceso");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://35.237.92.42:8084/ControlDeAcceso/consultaControlAcceso?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACONTROLACCESO_WSDL_LOCATION = url;
        CONSULTACONTROLACCESO_EXCEPTION = e;
    }

    public ConsultaControlAcceso_Service() {
        super(__getWsdlLocation(), CONSULTACONTROLACCESO_QNAME);
    }

    public ConsultaControlAcceso_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACONTROLACCESO_QNAME, features);
    }

    public ConsultaControlAcceso_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACONTROLACCESO_QNAME);
    }

    public ConsultaControlAcceso_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACONTROLACCESO_QNAME, features);
    }

    public ConsultaControlAcceso_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaControlAcceso_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaControlAcceso
     */
    @WebEndpoint(name = "consultaControlAccesoPort")
    public ConsultaControlAcceso getConsultaControlAccesoPort() {
        return super.getPort(new QName("http://controldeacceso.portafolio.com/", "consultaControlAccesoPort"), ConsultaControlAcceso.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaControlAcceso
     */
    @WebEndpoint(name = "consultaControlAccesoPort")
    public ConsultaControlAcceso getConsultaControlAccesoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controldeacceso.portafolio.com/", "consultaControlAccesoPort"), ConsultaControlAcceso.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACONTROLACCESO_EXCEPTION!= null) {
            throw CONSULTACONTROLACCESO_EXCEPTION;
        }
        return CONSULTACONTROLACCESO_WSDL_LOCATION;
    }

}
